# Generated by Django 5.2.10 on 2026-02-05 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_country_alter_state_name_state_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('total_complaints', models.IntegerField()),
                ('symptom_count', models.IntegerField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.village')),
            ],
        ),
    ]
