# Generated by Django 5.2.10 on 2026-02-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskrecord',
            options={'ordering': ['-calculated_at']},
        ),
    ]
