# Generated by Django 5.2.10 on 2026-02-05 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0002_country_alter_state_name_state_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.village'),
        ),
    ]
