# Generated by Django 5.2.10 on 2026-02-05 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_country_alter_state_name_state_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_fever', models.BooleanField(default=False)),
                ('has_diarrhea', models.BooleanField(default=False)),
                ('has_vomiting', models.BooleanField(default=False)),
                ('has_headache', models.BooleanField(default=False)),
                ('has_body_pain', models.BooleanField(default=False)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('mosquito_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('stagnant_water', models.BooleanField(default=False)),
                ('waste_issue', models.BooleanField(default=False)),
                ('water_contamination', models.BooleanField(default=False)),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('ai_suggestion', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.village')),
            ],
        ),
    ]
