# Generated by Django 5.2.10 on 2026-03-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_admin_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='parent_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_reports', to='complaints.complaint'),
        ),
    ]
