# Generated by Django 5.2.10 on 2026-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_assigned_at_complaint_field_visit_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='personal_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='personal_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
