# Generated by Django 5.2.10 on 2026-02-05 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('locations', '0002_country_alter_state_name_state_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('risk_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.riskrecord')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.village')),
            ],
        ),
    ]
