# Generated by Django 5.2.10 on 2026-03-20 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_riskrecord_options'),
        ('complaints', '0004_complaint_assigned_at_complaint_field_visit_due_at_and_more'),
        ('locations', '0002_country_alter_state_name_state_country'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('risk_alert', 'Risk Alert'), ('assignment', 'Assignment'), ('resolution', 'Resolution'), ('escalation', 'Escalation'), ('system', 'System')], default='risk_alert', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='risk_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.riskrecord'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.village'),
        ),
    ]
